from typing import Set

LOG_RECORD_STANDARD_ATTRS: Set[str] = {
    "args",
    "asctime",
    "created",
    "exc_info",
    "exc_text",
    "filename",
    "funcName",
    "levelname",
    "levelno",
    "lineno",
    "message",
    "module",
    "msecs",
    "msg",
    "name",
    "pathname",
    "process",
    "processName",
    "relativeCreated",
    "stack_info",
    "thread",
    "threadName",
    "service",
    "environment",
    "correlation_id",
    "request_id",
    "timestamp",
    "level",
    "logger",
    "exception",
    "exception_type",
    "exception_traceback",
    "exception_message",
    "extra",
}
